name: Auto-Promote Changes to Production

on:
  push:
    branches:
      - staging

jobs:
  auto-promote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run automated tests
      uses: my-org/my-test-action@v1
      with:
        target: staging

    - name: Promote to production
      if: success()
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout main
        git merge --no-ff staging
        git push origin main

